fib($x)=fib($x-1)+fib($x-2)
fib(1)=1
fib(2)=1

($x)=$x
{$a} = $a
$a is $b = $a is $b

nil+cons($x, $y)=cons($x, $y)
nil+nil = nil

cons($x, $y)+$z= cons($x, $y+$z)

True = True
False = False
not $a = not $a
not True = False
not False = True
$a and $b = False
True and True = True

if True $x else $y = $x
if False $x else $y = $y
if $z $x else $y = if $z $x else $y

reverse(nil)=nil
reverse(cons($a,$b))=reverse($b)+[$a]

nil[$x] = nil
$a[$x] = $a[$x]
cons($a,$b)[0]=$a
cons($a,$b)[$x]=if $x>0 $b[$x-1] else cons($a, $b)[$x % len(cons($a, $b))]

$a[:$x] = $a[:$x]
nil[:$x]= nil
cons($a, $b)[:0]= nil
cons($a, $b)[:$x] = if $x>0 cons($a,$b[:$x-1]) else cons($a, $b)[:$x % len(cons($a, $b))]

$a[$x:] = $a[$x:]
nil[$x:] = nil
$a[0:] = $a
cons($a,$b)[$x:] = if $x>0 $b[$x-1:] else cons($a, $b)[$x % len(cons($a, $b)):]

$a[$x:$y]=$a[:$y][$x:]

len($a)=len($a)
len(nil) = 0
len(cons($a, $b)) = 1+len($b)

nil is nil = True
nil is $a = False
char($a) is char($b) = $a is $b
cons($a, $b) is cons($c, $d) = ($a is $c) and ($b is $d)
str($a) is str($b) = $a is $b
str($a)[$b]=str($a[$b])
str($a) + str($b) = str($a + $b)
len(str($a)) = len($a)
str($a)[:$b]=str($a[:$b])
str($a)[$b:]=str($a[$b:])
str($a)[$x:$y]=str($a[$x:$y])

sock = socket()
nick = "LarkBot"
host ="irc.pdgn.co"
port = 6697
main = {sock.open "irc.pdgn.co" 6697
        sock.send "NICK " + nick +"\r\n"
        sock.send "USER " + nick + " "+host+" bla :" + nick + "%s\r\n"
        sock.recv 1024
      }
